version: "3.8"

services:
  redpanda:
    image: redpandadata/redpanda:latest
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 1G
      --reserve-memory 0M
      --node-id 0
      --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:9093
    ports:
      - "9092:9092"   # internal (containers use redpanda:9092)
      - "9093:9093"   # external (host uses localhost:9093)
      - "9644:9644"

  console:
    image: redpandadata/console:latest
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
      REDPANDA_ADMIN_URL: http://redpanda:9644
    depends_on:
      - redpanda
